### ISSUE TITLE
Doesn't install correctly in 1.10.0

### ISSUE THREAD

**Issue by cristan** [Kylemc1413/MappingExtensions#10]
If I install this via ModAssistant (1.1.9, currently the latest version) and then restart ModAssistant, I see the installed version set to 1.4.1, but the checkmark before isn't checked (unlike all the other installed mods).

It also doesn't seem to work: when I try to play [Amaranthe - The Nexus](https://beatsaver.com/beatmap/a62e) I get an infinite loader and I can't play this level (the same thing happens when I deinstall MappingExtensions).

**Comment by Kylemc1413** [comment]
That map loads fine on 1.10.0 with the latest version of mapping extensions from ModAssistant, having just tested. It's likely your download of the map or something else in your installation/data is corrupted or conflicting, as for the first part of your "issue", questions/issues about ModAssistant should either be on the repository for ModAssistant or preferably in the support channel of the BSMG Discord
