### ISSUE TITLE
Left Handed mode, No Obstacles mode, and No Bombs mode don't work

### ISSUE THREAD

**Issue by CharlieUK04** [Kylemc1413/MappingExtensions#12]
as stated Left Handed mode, No Obstacles mode, and No Bombs mode don't work as of one of the updates (it worked before idk the exact update) and just shows a black screen

**Comment by Kylemc1413** [comment]
This is not an issue with mapping extensions, remove CustomJSONData if you want those modes to work as intended on Mapping Extensions maps

**Comment by CharlieUK04** [comment]
then why does that file exist if it breaks left handed mode etc? what does it do?

**Comment by Kylemc1413** [comment]
It's a mod used by other mods that are not mapping extensions
