### ISSUE TITLE
NullReferenceException when restarting a specific song

### ISSUE THREAD

**Issue by Kuurama** [Kylemc1413/MappingExtensions#14]
When you start the map (on any diff) : https://beatsaver.com/maps/6cb3
everything go well without any error in the console, until you try to replay it => NullReferenceException happen.
To replay the map you need to play an other map once before being able to play it again.
Here is the log containing the error.
[_latest.log](https://github.com/Kylemc1413/MappingExtensions/files/7319081/_latest.log)

Here is a video showing the issue : https://streamable.com/2t5h5q

**Comment by Kylemc1413** [comment]
Can you please let me know if the issue occurs with Camera2 and BeatSaviorData not present and send a new log if it does

**Comment by Kuurama** [comment]
It doesn't happen if i remove camera2, here is the logs with camera 2 (but without beatsaviordata), beat savior data doesn't seems to cause issues.
[_latest.log](https://github.com/Kylemc1413/MappingExtensions/files/7319112/_latest.log)

**Comment by Kylemc1413** [comment]
Found the issue, will fix tomorrow

**Comment by Kylemc1413** [comment]
Should be fixed as of version 1.6.1 which is currently pending on beatmods
[MappingExtensions 1.6.1.zip](https://github.com/Kylemc1413/MappingExtensions/files/7325454/MappingExtensions.1.6.1.zip)
