### ISSUE TITLE
[Question] 1.20 update

### ISSUE THREAD

**Issue by MeDrioX** [Kylemc1413/MappingExtensions#18]
Hello,

Do you have a date for the mod update to Beat Saber 1.20?

Thanking you.

**Comment by Meivyn** [comment]
It is on Mod Assistant already.

**Comment by MeDrioX** [comment]
Mod Assistant is Quest 2 compatible?
Edit: My question was stupid. It's only for PC. Do you plan to release the mod for the Quest?

**Comment by Meivyn** [comment]
Pretty sure there is already a port for Quest, but it is incompatible with NoodleExtensions (and broken as far as I remember).

**Comment by MeDrioX** [comment]
I don't use NE except in 1.19.1. But I couldn't find the ME .qmod file for the Quest. Would you have a source?
Or maybe I misunderstood your message. I am not an English speaker so I apologize in advance for my English.

**Comment by Meivyn** [comment]
It is unlikely to be compatible with 1.20.0, but sorry, I can't really help you there, Quest modding is another world that I have no clue about.
