### ISSUE TITLE
Black screen when trying to load into any song [v1.20]

### ISSUE THREAD

**Issue by Jake-Thomas-Hall** [Kylemc1413/MappingExtensions#19]
Experiencing an issue when trying to play (seemingly) any map, where it gets stuck on a black screen, found that the base game worked unmodded, so started trying to narrow it down to which mod is causing this.

Installing mods one at a time, I found the behaviour only started once MappingExtensions was installed.

All mods installed were as follows:

- yt-dlp (yt-dlp): 2022.2.4
- FFmpeg (ffmpeg): 4.3.3
- Beat Saber IPA (BSIPA): 4.2.2
- BeatSaberMarkupLanguage (BeatSaberMarkupLanguage): 1.6.3
- INI Parser (Ini Parser): 2.5.9
- BS_Utils (BS Utils): 1.12.0
- SongCore (SongCore): 3.9.5
- SiraUtil (SiraUtil): 3.0.5
- BeatSaverVoting (BeatSaverVoting): 2.3.4
- Counters+ (Counters+): 2.2.7
- MappingExtensions (MappingExtensions): 1.7.0
- Cinema (BeatSaberCinema): 1.4.18
- Camera2 (Camera2): 0.6.90

Full log file attached. To try and keep the logs as verbose as possible: simply ran game, played one of the base maps, left it stuck on the black screen for that map for a moment, then closed the game.

On Windows Version 10.0.19044 Build 19044

[_latest.log](https://github.com/Kylemc1413/MappingExtensions/files/8306889/_latest.log)

Couldn't locate any other log files that looked relevant, let me know if there is more information needed to try and replicate this issue.

**Comment by Meivyn** [comment]
That is an issue with BSIPA, would you mind opening an issue on its repo instead?
To fix it though, close your game, then delete `UserData\Beat Saber IPA.json` and you should be fine after relaunching the game.

**Comment by Jake-Thomas-Hall** [comment]
Sure, can you share link to the BSIPA repo?

**Comment by Meivyn** [comment]
There: https://github.com/bsmg/BeatSaber-IPA-Reloaded/issues

**Comment by cronus130** [comment]
> That is an issue with BSIPA, would you mind opening an issue on its repo instead? To fix it though, close your game, then delete `UserData\Beat Saber IPA.json` and you should be fine after relaunching the game.

Thanks, confirming this worked for me.
