### ISSUE TITLE
MappingExtensions wont show up when in beat saber folder in beat saber version 1.0.0

### ISSUE THREAD

**Issue by theVRperson** [Kylemc1413/MappingExtensions#2]
![20190522220405_1](https://user-images.githubusercontent.com/50557291/58220708-e5692280-7cdd-11e9-832a-22f3cae528af.jpg)

**Comment by Kylemc1413** [comment]
What do you mean "In Beat Saber Folder"

**Comment by theVRperson** [comment]
i put mapping extensions in beat saber plugin folder and it wont load up...

**Comment by Kylemc1413** [comment]
Download the mod using the mod installer
