### ISSUE TITLE
How do i compile???

### ISSUE THREAD

**Issue by TNT-King** [Kylemc1413/MappingExtensions#20]

**Comment by Kylemc1413** [comment]
Opening the project in Visual Studio, adding necessary references to any dependencies, and compiling

**Comment by TNT-King** [comment]
What references do i need to add???

**Comment by TNT-King** [comment]
Or i mean, where can i get the DLLs???

**Comment by Kylemc1413** [comment]
If you have questions about beat saber modding in general like those you just asked, you should refer to the Beat Saber Modding Group Wiki or ask in the mod development channels in the discord.
