### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by N0odleLeg** [Kylemc1413/MappingExtensions#21]
i tried to use it to play the up and down map, and the amp plays like normal without any of the special features...
It might be becaus4e it's on 1.21, idk but it's kind of annoying

**Comment by Meivyn** [comment]
Can you please link the map you are talking about? Would also like if you can provide your logs (`Logs\_latest.log`) after trying the map.

**Comment by Meivyn** [comment]
Closing as I didn't get any answer in a week.
