### ISSUE TITLE
Feature request: toggle swap on left-handed mode

### ISSUE THREAD

**Issue by queengooborg** [Kylemc1413/MappingExtensions#22]
Being left-handed, I'm always disappointed when a VR game doesn't consider left-handed players and enforces the use of the right hand as the primary hand.  I'm happy that Beat Saber is not one of those games, with their left-handed mode to flip everything horizontally and swap the block colors.  However, this also includes walls, which includes decorative walls, causing text to be flipped and providing a not-as-pleasant experience.

I would love to see a feature included where notes, walls and bombs can be told to remain on their respective side, something like `_stayOnLeftHanded`, so that decorative walls and notes that follow a direction indicated in the song (FitBeat is a great example of such a song) will not flip to the other side if the player is left-handed!

_Notice: I'm not a mapper or modder, just a player who also writes code._

**Comment by Meivyn** [comment]
This is likely not possible in the current state of Mapping Extensions as it is overloading base game fields. It doesn't make use of a custom implementation and adding this would require a complete rewrite, which is somewhat planned but definitely not soon.

[Noodle Extensions](https://github.com/Aeroluna/Heck) is likely gonna be a better candidate for this, as it already makes use of custom fields with [CustomJSONData](https://github.com/Aeroluna/CustomJSONData). This library however is not thread-safe and it would require some rewrite on its part as well if we want to start using it. Currently, it will cause deadlocks if the player have both ME (using CJD) and NE installed.
