### ISSUE TITLE
Allow negative precise width according to precission placement

### ISSUE THREAD

**Issue by spookyGh0st** [Kylemc1413/MappingExtensions#4]
According to the README only negative precise width is allowed. It would be great, if it would be changed according to the precision placement formula to create precise fake walls.

So the with -1000 would be the equivalent of 0 width, -2000 the equivalent of -1 width, etc etc

**Comment by Kylemc1413** [comment]
Negative precision values are now supported for both width and height of walls as of mapping extensions for 1.20.0 of beat saber and beatmap format v3
