### ISSUE TITLE
Blocks outside of the 4 lane zone aren't hitable

### ISSUE THREAD

**Issue by 200Tigersbloxed** [Kylemc1413/MappingExtensions#5]
I'm on mapping extensions 1.3.0 with Beat Saber 1.3.0, when I play a 6 lane song (or any lane bigger than 4) the blocks can't be hit. If I try to hit the blocks the sabers just go right through them and is just counted as a miss. The blocks and barriers will load in, you just can't hit blocks in a 6 lane, 8 lane, etc.

**Comment by Kylemc1413** [comment]
You're playing a map that doesn't require mapping extensions. Mapping Extensions only works on maps that properly require it as of version 1.3.0. Your best bet is to contact the mapper to fix the map
