### ISSUE TITLE
Feature Request: Remove fake glow geometry from walls

### ISSUE THREAD

**Issue by RobertCordingly** [Kylemc1413/MappingExtensions#6]
It would be really nice if this mod removed the fake glow geometry from walls. It causes maps that use a lot of walls, such as Air, to look a lot worse. This also would likely improve performance some.

This might be better being it's own mod but it would be really nice either way.

**Comment by Kylemc1413** [comment]
Doesn't that only exist if you specifically use the lower quality walls?

**Comment by RobertCordingly** [comment]
I am dumb. I thought this github was for the Quest mapping extensions mod. This feature request would be for that, where you don’t get a choice of wall quality.
