### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by Thomasbomb** [Kylemc1413/MappingExtensions#7]
Consider adding installation instructions to the Readme

**Comment by Kylemc1413** [comment]
The mod can just be installed with mod assistant so I don't see that as necessary

**Comment by Alanimus** [comment]
This would be useful in cases like now, where you might have to install it manually with a different version of beatsaber. The reason is if you roll back and try using mod assistant will try overwriting newer plugin versions with old.

**Comment by Kylemc1413** [comment]
And the bsmg wiki explains how to manually install mods in general, rendering such a thing pointless to add to any individual mod that has standard installation

**Comment by kamoteshake** [comment]
Maybe a good compromise is to add a link to the [wiki](https://bsmg.wiki/pc-modding.html#install-mods)?

**Comment by similarion** [comment]
How do I install Mapping Extensions onto my Oculus Quest that has SideQuest/BMBF? I tried dragging the zip or the MappingExtensions.dll into BMBF but it says "Unable to Import File""File Failed to Process"

**Comment by sodiboo** [comment]
> 
> 
> How do I install Mapping Extensions onto my Oculus Quest that has SideQuest/BMBF? I tried dragging the zip or the MappingExtensions.dll into BMBF but it says "Unable to Import File""File Failed to Process"

it's a pc mod...

**Comment by Kylemc1413** [comment]
By installing the quest version of the mod from the #quest-mods channel in bsmg
